---
- hosts: test_servers
  become: yes
  tasks:
    - name: Create a directory if it does not exist
      file:
        path: /var/log/sudo
        state: directory
        mode: '0755'
        
    - name: copy file
      copy:
        src: ./files/sudo.cnf
        dest: /etc/sudoers.d/sudocnf
        mode: 0755
        owner: root
        group: root
