---
- hosts: test_servers
  become: yes
  vars_files:
    - ../vars/user-list-var.yml
  tasks:
    - name: Create user
      user:
        state: absent #ユーザを削除するときはコメントアウトを外す
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        groups:  "{{ item.group }}"
        shell: /bin/bash
      with_items:
        - "{{ users }}"
      when: users #usersが1件以上の場合のみ実行ß

    - name: create takkatao
      user:
        name: 'takkatao'
        groups: 'users, sudo, user42'

    - name: create kayumi
      user:
        name: 'kayumi'
        groups: 'users, sudo, user42, evaluating'
