version: '3'
services:
  nginx:
    build: ./requirements/nginx
    image: nginx:inception
    container_name: nginx
    ports:
      - 443:443
    env_file:
      - .env
    depends_on:
      - wordpress
    volumes:
      - ../data/wordpress_volume:/var/www/localhost

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:inception
    container_name: wordpress
    expose:
      - 9000
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ../data/wordpress_volume:/var/www/localhost

  mariadb:
    build: ./requirements/mariadb
    image: mariadb:inception
    container_name: mariadb
    expose:
      - 3306
    env_file:
      - .env
    healthcheck:
        test: mysqladmin ping -h 127.0.0.1 -u$$MARIADB_USER -p$$MARIADB_PASSWORD
