version: '3'
services:
  nginx:
    build: ./requirements/nginx
    image: nginx:inception
    container_name: nginx
    restart: always
    networks:
      - inception_network
    ports:
      - 443:443
    env_file:
      - .env
    depends_on:
      - wordpress
    volumes:
      - wordpress_volume:/var/www/localhost

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:inception
    container_name: wordpress
    restart: always
    networks:
      - inception_network
    expose:
      - 9000
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress_volume:/var/www/localhost

  mariadb:
    build: ./requirements/mariadb
    image: mariadb:inception
    container_name: mariadb
    restart: always
    networks:
      - inception_network
    expose:
      - 3306
    env_file:
      - .env
    volumes:
      - mariadb_volume:/var/lib/mysql
    healthcheck:
        test: mysqladmin ping -h 127.0.0.1 -u$$MARIADB_USER -p$$MARIADB_PASSWORD
        interval: 2s
        timeout: 2s
        retries: 5
        start_period: "30s"

networks:
  inception_network:
    driver: bridge

volumes:
  mariadb_volume:
    driver: local
#    driver_opts:
#      type: none
#      device: ../data/mysql
#      o: bind

  wordpress_volume:
    driver: local
#    driver_opts:
#      type: none
#      device: ../data/wordpress
#      o: bind
