version: '3'
services:

  ft_server:
    build: ./requirements/ft_server
    image: ft_serrver:inception
    container_name: ft_server
    ports:
      - 443:443
    expose:
      - 9000
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    build: ./requirements/mariadb
    image: mariadb:inception
    container_name: mariadb
    expose:
      - 3306
    env_file:
      - .env
    healthcheck:
        test: mysqladmin ping -h 127.0.0.1 -u$$MARIADB_USER -p$$MARIADB_PASSWORD